server:
  port: 8280
spring:
  application:
    name: subscription-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:root}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/fooddeliveryapp_subscriptionservice_db}
    username: ${DB_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Log Configuration
logging:
  level:
    root: INFO
    com:
      demo:
        spring: TRACE

# Eureka Client
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

# Prometheus
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'